chore: add support for abortSignals
oramasearch/oramacloud-client-javascript pull request #34
Opened 2024-08-22 00:48 UTC by crutchcorn

This PR adds support for abort signals while retaining support for AbortControllers, since we don't need the controller itself to cancel requests

2024-08-22 00:49 UTC, crutchcorn commented
This PR will need to be formatted and tested, since I don't have Bun installed on Windows

2024-08-22 04:12 UTC, micheleriva requested changes

2024-08-22 04:12 UTC, micheleriva commented on src/client.ts
> +  return signal && (signal as AbortController)?.signal !== undefined
This should probably be:

```
function isAbortController(signal: AbortSignal | AbortController | undefined): signal is AbortController {
  return signal !== undefined && (signal as AbortController)?.signal !== undefined
}
```

2024-09-12 11:07 UTC, crutchcorn commented
@micheleriva, please re-review!

2024-10-29 10:09 UTC, merged